[toolchain]
channel = "stable"
components = ["rustfmt", "clippy"]
targets = ["aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
